cregex: cregex.o
	g++ ./cregex.o  /home/ansen/muduo/release/lib/libmuduo_net.a /home/ansen/muduo/release/lib/libmuduo_base.a -lpthread -o cregex
cregex.o: cregex.cc
	g++ -I/home/ansen/muduo -c cregex.cc

